---
language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install "ansible==1.8"
script:
  - "echo $'[defaults]\nroles_path = ../' > ansible.cfg"
  - ansible-playbook -i tests/inventory/test.inv --syntax-check tests/test.yml
  - ansible-playbook -i tests/inventory/test.inv --connection=local --sudo -vvvv tests/test.yml
notifications:
  email: false
