---
# Install logrotate package.
- name: Install logrotate
  apt:
    pkg=logrotate={{ logrotate_version }}
    state=present

# Deploy the configuration file.

- name: "Set up logrotate configuration"
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ item.name }}"
  with_items: logrotate_configs
  when: logrotate_configs is defined

